n=int(input())
print(n*'*'," "*(2*(n-1)-1),n*'*',sep="")
for i in range(n-2):
    print(" "*(i+1),end="")
    print("*",end="")
    print(" "*(n-2),end="")
    print("*",end="")
    print(" "*(2*(n-2-i)-1),end="")
    print("*",end="")
    print(" "*(n-2),end="")
    print("*")
print(" "*(n-1),end="")
print("*",end="")
print(" "*(n-2),end="")
print("*",end="")
print(" "*(n-2),end="")
print("*")
for i in range(n-3,-1,-1):
    print(" "*(i+1),end="")
    print("*",end="")
    print(" "*(n-2),end="")
    print("*",end="")
    print(" "*(2*(n-2-i)-1),end="")
    print("*",end="")
    print(" "*(n-2),end="")
    print("*")
print(n*'*'," "*(2*(n-1)-1),n*'*',sep="")